DROP TABLE MEMS;
CREATE TABLE MEMS
(
ID VARCHAR2(10) PRIMARY KEY,
PWD VARCHAR2(10),
EMAIL VARCHAR2(15),
PHONE VARCHAR2(15),
REGDATE DATE
);
INSERT INTO MEMS VALUES('no', '123', 'n@naver', '010-111', SYSDATE);
COMMIT;